# Generated by Django 5.2.11 on 2026-09-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_lms", "0005_alter_surveyresponse_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avlearners",
            name="program_status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("in_progress", "In Progress"),
                    ("—", "—"),
                ],
                default="in_progress",
                max_length=16,
            ),
        ),
    ]