# Generated by Django 5.2.11 on 2026-09-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_lms', '0006_alter_avlearners_program_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avsummary',
            name='av_checkpoints_completed',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=10),
        ),
    ]
